# -*- coding: utf-8 -*-
"""Untitled74.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uSqkZqO8Y7wBL05TLbn35PXsdacLYZAl
"""

!pip install pyvtk

import sys
from pyvtk import *

pts_2 = []
for k in range(80):
  for j in range(100):
    for i in range(100):
      pts_2.append([i,j,k])

vtk_2_frm = VtkData(\
        UnstructuredGrid(pts_2,
                         hexahedron=[[700000,700040,701040,701000,0,40,1040,1000],
                                      [700050,700099,701089,701050,50,99,1089,1050],
                                      [40,45,1045,1040,600040,500045,501045,601040],
                                      [45,50,1050,1045,500045,600050,601050,501045],
                                      [99,9999,9989,1089,700099,799999,799989,701089],
                                     [1000,1089,9989,9900,101000,101089,109989,109900]],
                          triangle=[[105900,105989,775989],[106900,106989,776989]],
                          quad = [[105900,106900,776989,775989]]
                         ),
        PointData(Scalars(range(len(pts_2)))),
        'Unstructured Grid Example'
        )
vtk_2_frm.tofile('example_large_it=9')